# Test your FastAPI endpoints

# get a list of all books
GET http://127.0.0.1:8000/books/
Accept: application/json

###

# get information for a specific book
GET http://127.0.0.1:8000/books/?_id=345435
Accept: application/json

###

# adding a new book to the database
POST http://127.0.0.1:8000/add-book/
Accept: application/json
Content-Type: application/json

{
  "title": "Olasılıksız",
  "author": "Adam Fawer"
}

###