# Test your FastAPI endpoints

# get a list of all books
GET http://127.0.0.1:8000/books/
Accept: application/json

###

# get information for a specific book
GET http://127.0.0.1:8000/books/?id=630e739ce72dce20e544aaa2
Accept: application/json

###

# adding a new book to the database
POST http://127.0.0.1:8000/add-book/
Accept: application/json
Content-Type: application/json

{
  "title": "The C Programming Language. 2nd Edition",
  "author": "Dennis Ritchie, Brian Kernighan"
}

###


POST http://127.0.0.1:8000/user/
Accept: application/json
Content-Type: application/json

{
  "name": "uğur",
  "surname": "eren"
}

###
